### ISSUE TITLE
Suggestion: A function `Point2d u c -> Vector2d u c -> LineSegment2d u c`in module `LineSegment2d`

### ISSUE THREAD

**Issue by prange** [ianmackenzie/elm-geometry#110]

**Comment by prange** [comment]
A function `Point2d u c -> Vector2d u c -> LineSegment2d u c`in module `LineSegment2d`

**Comment by ianmackenzie** [comment]
Any thoughts on what the function name would be? Brainstorming a bit:

```elm
LineSegment2d.fromStartPointAndDisplacement
LineSegment2d.fromDisplacement
LineSegment2d.sweep
LineSegment2d.extrusion
```

And just to make sure, I'm assuming the function would be the equivalent of doing

```elm
LineSegment2d.fromEndpoints
    ( startPoint
    , startPoint |> Point2d.translateBy displacement
    )
```

?

**Comment by MartinSStewart** [comment]
I agree this would be a useful function to have. I've ended up writing 
```elm
LineSegment2d.fromEndpoints
    ( startPoint
    , startPoint |> Point2d.translateBy displacement
    )
```
a lot so it would be nice to have shorthand for it. As for the name, what about `LineSegment2d.fromPointAndOffset` or `LineSegment2d.fromPointAndVector`? Otherwise, I think `LineSegment2d.fromDisplacement` sounds fine too.

**Comment by ianmackenzie** [comment]
`fromPointAndVector` seems pretty good, especially given that there is a matching `vector` accessor. Should be able to throw this into the next release which I'm getting ready to publish =)
