### ISSUE TITLE
Add Vector#d.sum

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-geometry#122]
e.g.

```elm
Vector2d.sum : List (Vector2d units coordinates) -> Vector2d units coordinates
```

which would be conceptually equivalent to

```elm
List.foldl Vector2d.plus Vector2d.zero
```

but should be implemented in an optimized, tail-recursive way to avoid allocating a bunch of intermediate temporary vector values.

**Comment by MartinSStewart** [comment]
I noticed these were missing when I was going to get the average of a list of `Vector3d`s. They were present in elm-geometry 1.2.1 so their disappearance was unexpected. Still it's pretty quick to just write my own with the code you provided in the meantime.

**Comment by ianmackenzie** [comment]
I'm confused - there _is_ a `Vector3d.sum` on https://package.elm-lang.org/packages/ianmackenzie/elm-geometry/1.2.1/Vector3d, but it's basically the same as the current `plus` (takes two vectors, not a list). Am I looking at the wrong thing?

**Comment by MartinSStewart** [comment]
My mistake, I was misremembering things. I had used Quantity.sum which takes a list of values. When I didn't see a sum function in elm geometry 3 I knew I had seen it somewhere before and thought it was elm geometry 1.2.1.

**Comment by ianmackenzie** [comment]
Gotcha, makes sense! Anyways, it's in now, will hopefully push out a 3.2 release shortly with it included.
