### ISSUE TITLE
Add velocity/acceleration/force vector constructors?

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-geometry#127]
`Vector3d.kilometersPerHour`, `Vector3d.metersPerSecondSquared`, `Vector3d.newtons` etc.

Would be quite a few extra functions but could make working with things like `elm-physics` more convenient.

**Comment by ianmackenzie** [comment]
Perhaps put these in a 'Physics' section or similar towards the bottom of the documentation, so that they don't clutter things up too much?

**Comment by g-belmonte** [comment]
Hmm... this seems interesting! Can I help out somehow? :smile:

**Comment by ianmackenzie** [comment]
Certainly! Feel free to take a crack at it, I'll assign this issue to you =)

Don't be shy about opening up a work-in-progress pull request once you have a bit of code in place - happy to provide feedback on an initial version, suggest additional constructors that might be useful, etc.

**Comment by ianmackenzie** [comment]
Implemented in #139, thanks @g-belmonte! It's possible we'll think of more units to add here in the future but I think for now this can be closed.
