### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by g-belmonte** [ianmackenzie/elm-geometry#141]
Hey there, @ianmackenzie !

When I tried to run `elm reactor` on the `sandbox` folder, I ran into one issue. The use `Skinney` was renamed to `robinheghan`, so we have that the dependency `Skinney/murmur3 2.0.8` is now `robinheghan/murmur3 1.0.0` (present on `sandbox/elm.json` and `benchmark/elm.json`(indirect dependency))

Also, I noticed that we have the old `elm-package.json` using the dependency `Skinney/elm-array-exploration`, which is not published as an elm packages anymore. It still exists as an [archived repository](https://github.com/robinheghan/elm-array-exploration) though. (present on `docs/interactive/elm-package.json` and `doc/images/elm-package.json`)

On the case of the `sandbox` we can uninstall the old `murmur3` package and install the new one. But as for the others, do we have any way to update them?

**Comment by ianmackenzie** [comment]
Good catch! I've switched over to `robinheghan/murmur3` in `sandbox` so hopefully that fixes the sandbox issue. The `docs` and `benchmarks` directories have gotten a bit out of date and will probably require a bit more work at some point to update, but those aren't really as critical so I think we can leave them for now.
