### ISSUE TITLE
Add point-in-polygon test

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-geometry#40]
Probably best approach is to use winding number: http://geomalgorithms.com/a03-_inclusion.html

However, this is still linear time in the number of polygon edges. Is there a more efficient approach for large, complex polygons? One idea would be to construct a triangulation of the polygon, store the triangles in an R-tree and then use that to determine which (if any) of the triangles a given point is contained in. However, for (say) the triangulation of a polygon approximating a circle (with many thin triangles crossing the entire polygon) there may still be O(n) triangles whose bounding box overlaps with any given point.

**Comment by gampleman** [comment]
AFAIK currently there is nothing that enforces the polygon vertices to be sorted, right? 

Won't this be a problem here? Because if we need to sort them, then we'll need to pay O(nlogn)...

**Comment by ianmackenzie** [comment]
I should probably add a note to the docs...constructors like `Polygon2d.fromVertices` **do** expect the vertices to be given in order (either clockwise or counterclockwise is OK, but random order is not). And I don't see how it could be otherwise - from a list of vertices in random order there's no way to tell which polygon was intended. For example, four vertices in a square with one vertex in the middle of the square might represent

```
o---o
 \  |
  o |
 /  |
o---o
```

or they might represent

```

o---o
|   |
| o |
|/ \|
o   o
```

and there's no way to determine automatically which one the user wants. Or am I misinterpreting your comment?

**Comment by gampleman** [comment]
That makes perfect sense. Perhaps a note in the docs would prevent others from asking such a stupid question :)

**Comment by ianmackenzie** [comment]
Added in #96.
