### ISSUE TITLE
Add Tolerance module

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-geometry#45]
Initial design:

```elm
type Tolerance
    = MaxError Float
    | MaxAngle Float
    | MinNumSegments Int
    | AllOf (List Tolerance)

Tolerance.maxError : Float -> Tolerance

Tolerance.maxAngle : Float -> Tolerance

Tolerance.minNumSegments : Int -> Tolerance

Tolerance.allOf : List Tolerance -> Tolerance

-- determine a required number of segments given a
-- max second derivative magnitude and a tolerance
Tolerance.numSegments : Float -> Tolerance -> Int
```

Should be able to be used by both curves and surfaces.

**Comment by altaic** [comment]
Should `AllOf` not be a `Set` or some such, rather than `List`?

Actually, is there a way to enforce something like that in Elm, where the partial type (i.e. `MaxError` as opposed to `MaxError Float`) dictates uniqueness? I guess there’d have to be additional constraints to prevent nested sets anyway, hmm. Sorry for the general sort of question on your tracker.

**Comment by ianmackenzie** [comment]
👋 @altaic! Generally always happy to have design discussions =)

It seemed to me that using a `List` was the simplest (and probably most lightweight/fastest given that `allOf` would typically only be given two or three arguments). And while something like

```elm
Tolerance.allOf [ Tolerance.maxError 0.01, Tolerance.maxError 0.00001 ]
```

might seem weird, it can certainly be sensibly well-defined (basically just choose the strictest - if something is accurate to within 0.00001 then it's also accurate to within 0.01!). So it didn't seem worth trying to do anything tricky to make things stricter.

That said, I've been playing a fair bit with this API - the current thinking is something simpler like

```elm
module Approximation

type Accuracy
    = MaxError Float
    | NumSteps Int

maxError : Float -> Accuracy

numSteps : Int -> Accuracy
```

which you would call as

```elm
CubicSpline3d.toPolyline (Approximation.maxError 0.001) spline
```

(Among other things, I realized that trying to put a tolerance on max angular error was difficult or impossible to do efficiently in the general case - although I have some ideas on how to implement a slightly relaxed version.)

**Comment by ianmackenzie** [comment]
`Accuracy` module added in revision 71b7d7555696f957ac774d36aec77f6c313257df.
