### ISSUE TITLE
ianmackenzie/elm-geometry does not appear on http://package.elm-lang.org/

### ISSUE THREAD

**Issue by ckoster22** [ianmackenzie/elm-geometry#46]
This package isn't visible on http://package.elm-lang.org/

**Comment by ianmackenzie** [comment]
Hey @ckoster22, apologies for the confusion - I'm just in the middle of renaming `opensolid/geometry` to `ianmackenzie/elm-geometry`, so I haven't published anything under the new name yet. In the meantime you should be able to use `opensolid/geometry` instead and it will be an easy transition to this package once I publish it. I've updated the README to hopefully make that more clear!
