### ISSUE TITLE
Add 'midpoint' functions to curve types

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-geometry#51]
Example signature:

```elm
CubicSpline2d.midpoint : ArcLengthParameterized -> Point2d
```

**Comment by MrL1605** [comment]
I would like to work on this issue. 
Let me know if there are any other inputs.

**Comment by MrL1605** [comment]
I would like some more help in this.

I tried to search for some resources as I didn't know how to calculate midpoints of curves myself, but couldn't find much.

If anyone has any resources for parameterized curves I can refer to, it would be great.

**Comment by MrL1605** [comment]
Following link is useful for Cubic Spline 
http://blog.sklambert.com/finding-the-control-points-of-a-bezier-curve/#finding-the-control-points

**Comment by MrL1605** [comment]
Hi @ianmackenzie, 
The signature you suggested includes ArcLengthParameterized
```ELM
CubicSpline2d.midpoint : ArcLengthParameterized -> Point2d
```
In case of CubicSpline2d I only need the end points and control points. 
Check changes in [above PR](https://github.com/ianmackenzie/elm-geometry/pull/85/commits/4323ec87b79200f329c80eb06439ce2fa2fc1b08#diff-fdd7fab72dfb5d5f41d11e168148810eR981)

As creating ArcLengthParameterized requires one to call build, it would be optimal to use following signature instead.
```ELM
CubicSpline2d.midpoint : CubicSpline2d -> Point2d
```

PS: I'll add more midpoint functions to other curves as well

**Comment by ianmackenzie** [comment]
Hey @MrL1605 I've replied in #85 - probably easiest to continue the discussion there.

**Comment by ianmackenzie** [comment]
Spline curve midpoint functions added in #85 - now just need circular and elliptical arc versions.
