### ISSUE TITLE
Add BoundingBox#d.expandBy

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-geometry#60]
`BoundingBox#d.expandBy : Float -> BoundingBox#d -> Maybe BoundingBox#d`

Use negative value to shrink, return `Nothing` if shrunken past zero width - can default to the original box or `BoundingBox#d.singleton (BoundingBox#d.centroid box)` if desired

**Comment by MrL1605** [comment]
I'm picking this issue up and I have a doubt relating to this issue.
If boundingBox is represented by : min (3,2) max (8,6) 
And it is expanded by 3
Then resulting boundingBox is represented by : (0,-1) (11,9)

Let me know if I'm incorrect.

**Comment by ianmackenzie** [comment]
That's correct!

**Comment by ianmackenzie** [comment]
Added in #82. Thanks @MrL1605!
