### ISSUE TITLE
Add centroid functions

### ISSUE THREAD

**Issue by ianmackenzie** [ianmackenzie/elm-geometry#64]
- [x] `Point#d.centroid : List Point#d -> Maybe Point#d`
- [ ] `Polygon2d.centroid : Polygon2d -> Maybe Point2d` (weight triangle centroids by signed area)
- [x] `Polyline#d.centroid : Polyline#d -> Maybe Point2d` (weight edges by length)

**Comment by davcamer** [comment]
@ianmackenzie Are you actively working on this? I am thinking of doing it as part of Hacktoberfest 🎃

**Comment by ianmackenzie** [comment]
@davcamer I am not - thanks for checking first! If you're willing to have a go, that would be great =)

I've actually just started a pretty huge refactoring (in a branch) to update `elm-geometry` to use my recently-released `elm-units` package for all coordinate etc. values, but I'm starting with low-level stuff like points and vectors. It will probably be a while before I get to polylines and polygons, so there shouldn't be any issue merging your changes into my branch before that happens. Even if I do get to polylines/polygons before you finish, any merge conflicts should be very easy to resolve, so please don't feel you need to rush.

**Comment by davcamer** [comment]
👍 

I was looking at some of the Hacktoberfest issues in `elm-units` as well, but I should stick to one at a time. They are both nice libraries.

I will start with Polygon centroids.

**Comment by ianmackenzie** [comment]
A couple implementation comments/suggestions off the top of my head:

  - Should return `Nothing` if the polyline/polygon has no points
  - `Polyline#d.centroid` will be a bit simpler than `Polygon2d.centroid` (but do whichever you'd prefer!)
  - For polylines, the simplest implementation would basically be to add up weighted line segment centroid coordinates and then divide by total weight at the end, but this would encounter roundoff issues if the coordinates were large (the polyline was far from the origin). A better approach would be:
    - Find the rough centroid by getting the centroid of the polyline's bounding box
    - Add up the vectors from that approximate centroid to each line segment's centroid, weighted by line segment length
    - Divide the vector sum by overall weight, then add to the initial approximate centroid
  - Similar for polygon centroid - for that you'll end up forming a bunch of triangles (one for each polygon edge), and it would be better to build those triangles from an approximate bounding box-based centroid instead of from the global origin

**Comment by davcamer** [comment]
Thank you for the suggestions. As soon as I started looking at polygon centroid implementations I started to think polylines might have been the better choice. Particularly the advice about avoiding overly large values I don't think I would have come across without your input.

**Comment by MrL1605** [comment]
I had picked this up yesterday, and should have commented on this.
Now that you have picked this up, I'll work on some other issue.
This link would be helpful. 
https://www.seas.upenn.edu/~sys502/extra_materials/Polygon%20Area%20and%20Centroid.pdf

**Comment by davcamer** [comment]
Thank you @MrL1605.

I have the algorithm written up but wanted to include a fuzz test. The only general invariant I could think of to test was "a polyline's centroid should be within the polyline's bounding box." However, because of imprecision with floating point math, even this invariant fails. Some examples:

```
Given (Point2d (0.000001,0.000001),Point2d (0.000001,0.000001),[Point2d (-4.000009976353613,0.000001)])

    Expected centroid Point2d (0.000001000000000139778,0.000001) to be within bounding box BoundingBox2d { maxX = 0.000001, maxY = 0.000001, minX = -4.000009976353613, minY = 0.000001 }.


Given (Point2d (0.000001,0.000001),Point2d (0.000001,0.000001),[Point2d (-4.00000993801419,0.000001)])

    Expected centroid Point2d (0.000001000000000139778,0.000001) to be within bounding box BoundingBox2d { maxX = 0.000001, maxY = 0.000001, minX = -4.00000993801419, minY = 0.000001 }.
```

Looking at the other tests, I thought it might be appropriate to add a function to Expect to check that a point is contained by a bounding box within a given tolerance. Implementation would be to add the tolerance to each side of the bounding box and use the existing contains function. Does this seem appropriate?

**Comment by davcamer** [comment]
I realized that in the above results I was not weighting edges according to their length. I have since done that, and included a "fuzzy" expectation for the bounding box contains method. Works continues...

**Comment by ianmackenzie** [comment]
First of all, apologies for the delayed response - I'm in the middle of a move, and in fact still don't have my computer set up so this is all from my phone. This all sounds good! Definitely makes sense to have a fuzzy bounding box inclusion test.

Other potential fuzz tests I can think of:

  - Centroid of a single segment polyline should be the midpoint of the two endpoints
  - More generally, if you generate a bunch of random distances and a random axis, sort the distances and then use `Point#d.along` to convert those distances to points along the axis, then form a polyline from those points, the centroid should still be at the midpoint of the start and end points

**Comment by davcamer** [comment]
No worries. I hope the move goes smoothly for you. 

I ended up thinking up the single line fuzz test too 😄. That axis one sounds interesting.

For the Polygon2d centroid, here is how I've understood the approach:
* Find the rough centroid (aka center of bounding box).
* Find vectors from rough centroid to the edges.
* Sum the vectors, weighting them by the area of a triangle from the rough centroid to the edge. This could include negative areas for concave polygons.

Have I understood that correctly?

**Comment by ianmackenzie** [comment]
Close - you'll actually want to use the vectors from the rough centroid to the centroid of the *triangle*, not the edge. Then as you say, weight each vector by the signed area of the triangle.

Conceptually, you're finding the center of mass of an *area* (like a sheet of paper or piece of wood in the shape of the polygon). You could do that by forming a triangulation of the polygon (breaking it up into individual chunks) and then doing a weighted average of the centers of mass of each chunk (triangle). It just turns out that it still works if you just form a bunch of triangles from a single origin to every edge - it's not a proper triangulation since the triangles may overlap each other, but by using the (possibly negative) signed area of the triangle as its weight it mathematically works out to the same thing.

For the polyline case, you're conceptually finding the center of mass of something more like a bent piece of wire, which you do by breaking that wire up into individual chunks (line segments) and forming a weighted average of those chunks.
