### ISSUE TITLE
keywords to make docs easier to search

### ISSUE THREAD

**Issue by 2mol** [ianmackenzie/elm-geometry#70]
Hi! Since in math vectors and points are usually treated like things you can "add" and multiply with scalars, I propose that the docs could be made marginally easier to search (with Ctrl-F for example) if those keywords appeared above the relevant functions.

The following would be a good start:

- "multiply a vector by a scalar" for the `scaleBy` functions
- "add a vector to a point" for `translateBy`

I will add more functions here as I come across them.

**Comment by ianmackenzie** [comment]
Resolved in 3a385743c7b25f246584caedd5e4734cf3e5c35f - I also added a note to `Vector#d.reverse` pointing out that it is basically `negate`. I think that should be most of the 'mathematical' functions, at least - so I'll close this for now, but feel free to reopen if you think of more examples!
