### ISSUE TITLE
Add scaleBy function that does componentwise scaling.

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-geometry#97]
I find I often need to scale a point or vector by another vector.  There doesn't seem to be any direct way of doing that in elm-geometry so I have to resort to code that looks like this
```
(sx, sy) = Vector2d.components scale
(x, y) = Point2d.coordinates point
newPoint = Point2d.fromCoordinates (x * sx, y * sy)
```
when what I'd like to do is
```
newPoint = Point2d.scaleBy scale point
```

**Comment by ianmackenzie** [comment]
You're probably going to get a longer answer here than you bargained for... =)

Can you share a bit more context about what you're trying to do? In general I try to avoid working directly with coordinates/components - to me a point is fundamentally a geometric point in space, and its X/Y coordinates are just its representation in some particular Cartesian coordinate system. For example, things like

```elm
Point2d.translateBy : Vector2d -> Point2d -> Point2d
Point2d.rotateAround : Point2d -> Float -> Point2d -> Point2d
Point2d.scaleAbout : Point2d -> Float -> Point2d -> Point2d
```

can be explained/defined entirely in geometric terms, and will have the same physical/geometric result regardless of what coordinate system is used to define the various points/vectors.

That's *not* true of something like the proposed `Point2d.scaleBy` - you'll get different results based on your choice of origin and choice of X/Y directions. The first issue you could solve by passing a scaling origin point to `Point2d.scaleBy`, but the second is harder.

Is there a way to describe what you want to do in geometric terms, without referring to X and Y components/coordinates? For what it's worth, there's an open issue to [allow scaling along arbitrary axes](https://github.com/ianmackenzie/elm-geometry/issues/80), but I don't know if that's what you need.

**Comment by MartinSStewart** [comment]
I'm working with webgl and writing code to generate 3d models of a circuit board.  Often I start with a primitive like a square or cube (made out of Point2ds or Point3ds respectively) and then scale it with a vector and add some offset.

Here for example, I have a 3d model of a transistor and I want to add a rectangle in the middle of it. The code for that looks like this
```
let
    ( x, y ) = Point2d.coordinates pos
    ( sx, sy ) = Vector2d.components size
in
mapEachVertex
    (\p ->
        let
            ( px, py ) = Point2d.coordinates p
        in
        { position =
            Point3d.fromCoordinates ( x + px * (sx - 1) + 0.5, y + py * (sy - 1) + 0.5, chipHeight + 0.01 )
                |> Point3d.toVec3
        , color = Vec4.vec4 0.4 0.4 0.4 1
        }
    )
    square
```
And here is a screenshot of what that looks like
![image](https://user-images.githubusercontent.com/5068391/56511172-37c2f200-652c-11e9-9f53-fc385c3763c0.png)

This is what the code looks like if there was a scaleBy (now with a point to scale about instead of always using the origin)
```
let
    scale = Vector2d.difference size (Vector2d.fromComponents (1, 1))
in
mapEachVertex
    (\p ->
        let
            (finalX, finalY) = 
                |> Point2d.scaleBy Point2d.origin scale
                |> Point2d.translateBy pos 
                |> Point2d.translateBy (Point2d.fromCoordinates (0.5, 0.5))
                |> Point2d.components
        in
        { position =
            Point3d.fromCoordinates ( finalX, finalY, chipHeight + 0.01 )
                |> Point3d.toVec3
        , color = Vec4.vec4 0.4 0.4 0.4 1
        }
    )
    square
```

I admit it turns out to be more lines of code but I think it's easier to read since we don't have the `x + px * (sx - 1) + 0.5, y + py * (sy - 1) + 0.5` section from before that obscures the fact that were just doing the same scaling and translations on both the x and y coordinates.

Lastly, I tried using scaleAlong and this is what it looks like
```
let
    scale = Vector2d.difference size (Vector2d.fromComponents (1, 1))
in
mapEachVertex
    (\p ->
        let
            (finalX, finalY) = 
                |> Point2d.scaleAlong Axis.x scale.xComponent
                |> Point2d.scaleAlong Axis.y scale.yComponent
                |> Point2d.translateBy pos 
                |> Point2d.translateBy (Point2d.fromCoordinates (0.5, 0.5))
                |> Point2d.components
        in
        { position =
            Point3d.fromCoordinates ( finalX, finalY, chipHeight + 0.01 )
                |> Point3d.toVec3
        , color = Vec4.vec4 0.4 0.4 0.4 1
        }
    )
    square
```
In this example I think this is a good compromise.  What I might do is implement scaleBy and scaleAlong locally and see how much the code improves one using one or the other.

**Comment by ianmackenzie** [comment]
Thanks for the detailed reply! Is there a reason you're modelling the shapes by starting with a primitive and then applying scale/offset? Is that fundamentally how your UI works (users start with a primitive and then manipulate it), are you personally most comfortable modelling shapes that way, or is there some other reason? My default reaction would be to make it easier to construct the final shape directly somehow, instead of by transformation of a primitive.

Also, is there a particular advantage to using a `Vector2d` to represent a size instead of just using a `( Float, Float )` tuple? To me vectors are for things like displacements and velocities where addition/dot product etc. make sense - to me it doesn't make sense to add two width/height pairs together.

**Comment by MartinSStewart** [comment]
The user lays out the circuit in a 2d view rendered with SVG. The 3d view is shown later so the UI isn't the reason I use primitives.

There are some places where I do construct shapes directly. For example, when constructing a tapered cube (for the top half of a transistor) I do this
```
let
    ( sx, sy ) =
        Vector2d.components size

    -- Top margin
    o =
        chipBaseMargin + 0.1

    -- Bottom margin
    b =
        chipBaseMargin

    height =
        0.2
in
[ -- Top
  ( Color.Manipulate.lighten 0.15 chipBaseColor
  , TriangleFan ( o, o, 1 ) ( o, sy - o, 1 ) ( sx - o, sy - o, 1 ) [ ( sx - o, o, 1 ) ]
  )

-- Back
, ( Color.Manipulate.lighten 0.06 chipBaseColor
  , TriangleFan ( b, b, 0 ) ( o, o, 1 ) ( sx - o, o, 1 ) [ ( sx - b, b, 0 ) ]
  )

-- Front
, ( Color.Manipulate.lighten 0.08 chipBaseColor
  , TriangleFan ( b, sy - b, 0 ) ( sx - b, sy - b, 0 ) ( sx - o, sy - o, 1 ) [ ( o, sy - o, 1 ) ]
  )

-- Left
, ( Color.Manipulate.lighten 0.12 chipBaseColor
  , TriangleFan ( b, b, 0 ) ( b, sy - b, 0 ) ( o, sy - o, 1 ) [ ( o, o, 1 ) ]
  )

-- Right
, ( Color.Manipulate.lighten 0.02 chipBaseColor
  , TriangleFan ( sx - b, b, 0 ) ( sx - o, o, 1 ) ( sx - o, sy - o, 1 ) [ ( sx - b, sy - b, 0 ) ]
  )
]
```
In this case I did it because I felt it was easier to define all the vertices directly than write code to transform a cube. In general though I think it's easier to understand "primitive plus transformation" code than it is to understand "define each point directly" code.  Additionally, when I define each point directly, I need to get the winding order correct so that the triangles defining my shape point outward, not inward. I basically always get this wrong for 50% of the triangles and have to trial and error my way forward.

I actually have a `Size` module that I've written. I've started removing it from my code though because there's often some function in elm-geometry that I need (and don't want to spend time reimplementing) so then I have to convert from Size to Vector2d, use that function, and then convert back.  This happens in enough places that I just decided to use Vector2d everywhere.

**Comment by ianmackenzie** [comment]
Very useful feedback! I probably do need to work more on supporting "primitive plus transformation" workflows. If `scaleAlong` is enough for what you need to do, great, but I'm also happy to consider other similar functions as long as they can be defined in a geometric instead of numerical way.

That said, I think in this case you could also do something like

```elm
makeRectangle : Point2d -> ( Float, Float ) -> Rectangle2d
makeRectangle position dimensions =
    Rectangle2d.centeredOn (Frame2d.atPoint position) dimensions
```

and then do whatever you need to with the rectangle's vertices.

(BTW I edited your comments slightly, just to highlight the code snippets as Elm so I could scan them a bit more easily...)

**Comment by MartinSStewart** [comment]
Thanks, I'll go ahead and use scaleAlong and see how it goes.

**Comment by ianmackenzie** [comment]
OK, sounds good - I'll close this issue, then, but feel free to open a new issue if `scaleAlong` doesn't work out or if you have ideas for other functions that would be useful.
